

version: '3.9'
 
services:
  mqtt:
    container_name: coldchain-mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - mynet
  influxdb:
    container_name: coldchain-influx
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dummy
      - DOCKER_INFLUXDB_INIT_ORG=se4gd
      - DOCKER_INFLUXDB_INIT_BUCKET=Coldchain
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=helloworld
    networks:
      - mynet
  telegraf:
    container_name: coldchain-telegraf
    image: telegraf
    restart: always
    volumes:
      # - ./telegraf:/telegraf/telegraf.conf
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
 
    depends_on:
      mqtt:
        condition: service_started
      influxdb:
        condition: service_started
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    networks:
      - mynet
  grafana:
    container_name: coldchain-grafana
    image: grafana/grafana
    # image: grafana/grafana-oss:8.4.3
    restart: always
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - mynet
    depends_on:
      influxdb:
        condition: service_started
  openhab:
    image: openhab/openhab
    container_name: coldchain-openhab
    restart: always
    networks:
      - mynet
    ports:
      - "9876:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
  reporter:
    image: reporter:latest
    container_name: coldchain-reporter
    restart: always
    networks:
      - mynet
    ports:
      - "8080:8080"
    depends_on:
      mqtt:
        condition: service_started
 
volumes:
  config:
  data:
  log:
  influxdb-storage:
 
networks:
  mynet:
 